server:
  port: 1920
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca?serverTimezone=America/Bogota
    username: root
    password:
  jpa:
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"