server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          [/*]: '[/**]'
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-catgoria
          uri: lb://service-catgoria
          predicates:
            - Path=/Categoria/**
        - id: service-editorial
          uri: lb://service-editorial
          predicates:
            - Path=/Editorial/**
        - id: service-libros
          uri: lb://service-libros
          predicates:
            - Path=/Libros/**
