server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8099/eureka/

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-catgoria
          uri: lb://service-catgoria
          predicates:
            - Path=/Categoria/**
        - id: service-editorial
          uri: lb://service-editorial
          predicates:
            - Path=/Editorial/**
        - id: service-libros
          uri: lb://service-libros
          predicates:
            - Path=/Libros/**
