#Data source 
#Indica el driver/lib para conectar java a mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Url donde esta el servicio de tu mysql y el nombre de la base de datos
#spring.datasource.url=jdbc:mysql://localhost:3306/empleado

#Usuario y contrasena para tu base de datos descrita en la linea anterior
#spring.datasource.username=root


#[opcional]Imprime en tu consola las instrucciones hechas en tu base de datos.
#spring.jpa.show-sql = true

server:
  port: 1920
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empleado?serverTimezone=America/Bogota
    username: root
    password:
  jpa:
    show-sql: true
